### ISSUE TITLE
Unable to find formwidget assets in whitelist apporach

### ISSUE THREAD

**Issue by CptMeatball** [SaifurRahmanMohsin/oc-txt-plugin#25]
![image](https://user-images.githubusercontent.com/1681727/60386169-04ec2b80-9a92-11e9-91bc-6d7f3e148930.png)

It seems that either the whitelist approach or the translate plugin (or a combination) causes the widget assets to 404. Latest OCMS build and latest plugin version.

**Comment by SaifurRahmanMohsin** [comment]
Ok... I see. Thanks for pointing this out. I’ll change the code to use the existing asset combiner, it should fix this issue.
